### ISSUE TITLE
Variable h_graphlets called before assignment

### ISSUE THREAD

**Issue by amblee0306** [mims-harvard/G-Meta#4]
Hi there, 

Thanks for making your code available to us. I would like to check what does h_graphlets refer to here (line 182) cause it seems to be called before assignment. Thanks! 

![image](https://user-images.githubusercontent.com/19768905/150812134-039f410f-a44f-4487-814f-7dc8d25f8ccf.png)

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late reply. this is an obsolete code. We actually never use when name = attention. so please ignore it. thanks
